class AlreadyExistsError(Exception):
    pass

class NotFoundError(Exception):
    pass
